p8105\_hw2\_jz3425
================
Jibei Zheng
10/2/2021

``` r
library(tidyverse)
library(readxl)
```

## Problem 1

Reading Mr. Trash Wheel dataset.

``` r
#read Mr. Trash Wheel data set and clean
mr_trash_wheel_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N534") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = round(sports_balls)) 

mr_trash_wheel_df
```

    ## # A tibble: 453 x 14
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ... with 443 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>

Reading precipitation data for 2018 and 2019.

``` r
#read precipitation data and create year variable
pre_18_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "2018 Precipitation", range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  mutate(year = 2018) %>% 
  relocate(year)

pre_19_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "2019 Precipitation", range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  mutate(year = 2019) %>% 
  relocate(year)

#combine 18 and 19 dataset and convert month to a character variable
precipitation_df = 
  bind_rows(pre_18_df, pre_19_df) %>% 
  mutate(month = month.name[month])

precipitation_df
```

    ## # A tibble: 26 x 3
    ##     year month     total
    ##    <dbl> <chr>     <dbl>
    ##  1  2018 January    0.94
    ##  2  2018 February   4.8 
    ##  3  2018 March      2.69
    ##  4  2018 April      4.69
    ##  5  2018 May        9.27
    ##  6  2018 June       4.77
    ##  7  2018 July      10.2 
    ##  8  2018 August     6.45
    ##  9  2018 September 10.5 
    ## 10  2018 October    2.12
    ## # ... with 16 more rows

The Mr. Trash Wheel dataset includes 453 dumpsters and 14 variables from
2014-2021. Data include weight\_tons, volume\_cubic\_yards of trash and
categories of trash: plastic\_bottles, polystyrene, cigarette\_butts,
glass\_bottles, grocery\_bags, chip\_bags, sports\_balls,
homes\_powered.

The precipitation dataset lists the precipitation for each month in 2018
and 2019.

The total precipitation in 2018 is 70.33.

The median number of sports balls in a dumpster in 2019 is 9.

## Problem 2

Reading pols-month dataset.

``` r
#read pols_month data and separate the date variable
pols_month_df = 
  read_csv("data/fivethirtyeight_datasets/pols-month.csv") %>% 
  separate(mon, into = c("year", "month", "day"), "-") %>% 
  mutate(month = as.numeric(month)) %>% 
  mutate(month = month.name[month]) %>% 
  mutate(year = as.numeric(year))

#create president variable
prez = factor(c("gop", "dem"))
pols_month_df = 
  mutate(pols_month_df, president = prez[prez_dem + 1]) %>% 
  select(-prez_gop, -prez_dem, -day)

pols_month_df
```

    ## # A tibble: 822 x 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <dbl> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <fct>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # ... with 812 more rows

Reading snp dataset.

``` r
#read and clean snp data
snp_df = 
  read_csv("data/fivethirtyeight_datasets/snp.csv")

snp_df_1 = snp_df[-c(176:787),] %>% 
  separate(date, into = c("year", "month", "day"), "/") %>% 
  mutate(year = as.numeric(year) + 2000)

snp_df_2 = snp_df[-c(1:175, 188:787),] %>% 
  separate(date, into = c("month", "day", "year"), "/") %>% 
  mutate(year = as.numeric(year) + 2000) %>% 
  relocate(year)

snp_df_3 = snp_df[-c(1:187),] %>% 
  separate(date, into = c("month", "day", "year"), "/") %>% 
  mutate(year = as.numeric(year) + 1900) %>% 
  relocate(year)

snp_df = bind_rows(snp_df_1, snp_df_2, snp_df_3) %>% 
  mutate(month = as.numeric(month)) %>% 
  arrange(year, month) %>% 
  mutate(month = month.name[month]) %>% 
  select(-day)

snp_df
```

    ## # A tibble: 787 x 3
    ##     year month     close
    ##    <dbl> <chr>     <dbl>
    ##  1  1950 January    17.0
    ##  2  1950 February   17.2
    ##  3  1950 March      17.3
    ##  4  1950 April      18.0
    ##  5  1950 May        18.8
    ##  6  1950 June       17.7
    ##  7  1950 July       17.8
    ##  8  1950 August     18.4
    ##  9  1950 September  19.5
    ## 10  1950 October    19.5
    ## # ... with 777 more rows

Reading unemployment dataset.

``` r
#read and clean unemployment dadta
unemp_df = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv", col_names = c("year", month.name), skip = 1) %>% 
  pivot_longer(
    January:December,
    names_to = "month",
    values_to = "unemployment"
    ) %>% 
  mutate(year = as.numeric(year))

unemp_df
```

    ## # A tibble: 816 x 3
    ##     year month     unemployment
    ##    <dbl> <chr>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ... with 806 more rows

Join the datasets.

``` r
#join plos_month_df and snp_df
temp = left_join(pols_month_df, snp_df)

#join unemp_df into it
final_df = left_join(temp, unemp_df)

final_df
```

    ## # A tibble: 960 x 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <fct>     <dbl>
    ##  1  1947 January      23      51     253      23      45     198 dem          NA
    ##  2  1947 Februa~      23      51     253      23      45     198 dem          NA
    ##  3  1947 March        23      51     253      23      45     198 dem          NA
    ##  4  1947 April        23      51     253      23      45     198 dem          NA
    ##  5  1947 May          23      51     253      23      45     198 dem          NA
    ##  6  1947 June         23      51     253      23      45     198 dem          NA
    ##  7  1947 July         23      51     253      23      45     198 dem          NA
    ##  8  1947 August       23      51     253      23      45     198 dem          NA
    ##  9  1947 Septem~      23      51     253      23      45     198 dem          NA
    ## 10  1947 October      23      51     253      23      45     198 dem          NA
    ## # ... with 950 more rows, and 1 more variable: unemployment <dbl>

The “pols\_month\_df” dataset contains 822 observations of 9 variables
related to the number of national politicians who are democratic or
republican at any given time from 1947-2015.

The “snp\_df” dataset contains 787 observatiosn of 3 variables related
to Standard & Poor’s stock market index from 1950-2012.

The “unemp\_df” dataset contains 816 observations of 3 variables related
to the percentage of unemployment in each month from 1948-2015.

The “final\_df” dataset joins these three datasets and contains 960
observations of 11 variables including president, snp index, percentage
of unemployment, from 1947-2015.

## Problem 3

Reading the popular baby names dataset.

``` r
#read and clean popular baby names dataset
names_df =
  read_csv("data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  mutate(gender = str_to_lower(gender)) %>% 
  mutate(ethnicity = str_to_lower(ethnicity)) %>% 
  mutate(childs_first_name = str_to_lower(childs_first_name)) %>% 
  distinct()
```

Producing a table showing the rank in popularity of the name “Olivia” as
a female baby name over time.

``` r
#create a table showing the rank in popularity of the name “Olivia” over time
olivia_df = 
  filter(names_df, childs_first_name == "olivia") %>% 
  arrange(year_of_birth) %>% 
  select(ethnicity, year_of_birth, rank) %>% 
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "rank"
  )

olivia_df
```

    ## # A tibble: 7 x 7
    ##   ethnicity                  `2011` `2012` `2013` `2014` `2015` `2016`
    ##   <chr>                       <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
    ## 1 asian and pacific islander      4     NA      3      1      1      1
    ## 2 black non hispanic             10     NA      6      8      4      8
    ## 3 hispanic                       18     22     22     16     16     13
    ## 4 white non hispanic              2     NA      1      1      1      1
    ## 5 asian and paci                 NA      3     NA     NA     NA     NA
    ## 6 black non hisp                 NA      8     NA     NA     NA     NA
    ## 7 white non hisp                 NA      4     NA     NA     NA     NA

Producing a table showing the most popular name among male children over
time.

``` r
#create a table showing the most popular name among male children over time
most_male_df= 
  filter(names_df, gender == "male", rank == 1) %>% 
  arrange(year_of_birth) %>% 
  select(-gender, -rank, -count) %>% 
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "childs_first_name"
  )

most_male_df
```

    ## # A tibble: 7 x 7
    ##   ethnicity                  `2011`  `2012` `2013` `2014` `2015` `2016`
    ##   <chr>                      <chr>   <chr>  <chr>  <chr>  <chr>  <chr> 
    ## 1 asian and pacific islander ethan   <NA>   jayden jayden jayden ethan 
    ## 2 black non hispanic         jayden  <NA>   ethan  ethan  noah   noah  
    ## 3 hispanic                   jayden  jayden jayden liam   liam   liam  
    ## 4 white non hispanic         michael <NA>   david  joseph david  joseph
    ## 5 asian and paci             <NA>    ryan   <NA>   <NA>   <NA>   <NA>  
    ## 6 black non hisp             <NA>    jayden <NA>   <NA>   <NA>   <NA>  
    ## 7 white non hisp             <NA>    joseph <NA>   <NA>   <NA>   <NA>

Producing a scatter plot for male, white non-hispanic children born in
2016.

``` r
#filter the dataset
scatter_df =
  filter(names_df, gender == "male", year_of_birth == 2016, ethnicity == "white non hispanic")

#produce a scatter plot
ggplot(scatter_df, aes(x = rank, y = count)) + geom_point()
```

![](p8105_hw2_jz3425_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->
